// The request body is read from a file
POST http://127.0.0.1:8080/list_fruit
Content-Type: application/json

< ./payloads/fruit.json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Small fruit is correct", function() {
  client.assert(response.body["small fruit"] === "grape", "Small fruit is not grape it is " + response.body["small fruit"]);
});

client.test("Medium fruit is correct", function() {
  client.assert(response.body["medium fruit"] === "apple", "Medium fruit is not apple");
});
%}

###
GET http://127.0.0.1:8080/
Accept: application/json

###

GET http://127.0.0.1:8080/fruit
Accept: application/json

> {%
   client.test("Request executed successfully", function() {
       client.assert(response.body["fruit"] === "Watermelon", "Wrong Fruit Type");
   });

%}

###